name = "Hamster"
uuid = "18155ac2-9efd-4ce8-82c3-162aa40282e9"
authors = ["martin <ga63loc@mytum.de>"]
version = "0.2.2"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeParzen = "eb66a70c-a255-11e9-03ea-7ba6b2f22006"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Arpack = "0.5.4"
BlockDiagonals = "0.2.0"
Clustering = "0.15.8"
DataStructures = "0.18.22"
HDF5 = "0.17.2"
MPI = "0.20.22"
OhMyThreads = "0.7.0"
Printf = "1.11.0"
Random = "1.11.0"
TreeParzen = "0.3.4"
UnPack = "1.0.2"
